services:
  api-backend:
    build:
      context: ./api-backend
      dockerfile: Dockerfile
    container_name: repuestos-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    volumes:
      - ./api-backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - erp-network

  web-frontend:
    build:
      context: ./web-frontend
      dockerfile: Dockerfile
    container_name: repuestos-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=${VITE_API_URL}
    volumes:
      - ./web-frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - erp-network

networks:
  erp-network:
    external:
      name: base-datos_default # Connecting to Project 1's network
